### PR TITLE
docs(diagrams): adding diagram and description for classes

### PR DESCRIPTION
**Pull request by misicaleksandar**

### CODE REVIEW

**Comment by NikolaMilosa** [comment]
NIT: Please change the title to follow convetional commits with SCOPE (example: docs(diagrams): ...)

**Comment by misicaleksandar** [comment]
> NIT: Please change the title to follow convetional commits with SCOPE (example: docs(diagrams): ...)

Done

**Comment by milandesancic** [comment]
We should use [class diagram](https://drawio-app.com/blog/uml-class-diagrams-in-draw-io/) here

**Review by NikolaMilosa — APPROVED** [review]
LGTM!

**Comment by NikolaMilosa** [comment]
Agree with the class diag, can we maybe add it as a point of improvement for the future @milandesancic?

**Review by niklson20 — DISMISSED** [review]
Looks good

**Review by niklson20 — APPROVED** [review]

**Review by NikolaMilosa — APPROVED** [review]

**Pull request merged**
